sonar.cpd.exclusions=GenHub/GenHub/Features/Info/Services/DefaultInfoContentProvider.cs,GenHub/GenHub/Features/Content/Services/**/*ProfileReconciler.cs,GenHub/GenHub.Core/Helpers/GameSettingsMapper.cs
sonar.coverage.exclusions=scripts/**
